### ISSUE TITLE
Please update dependencies version

### ISSUE THREAD

**Issue by se7ennlv** [andriyoganp/blue_print_pos#14]

**Comment by andriyoganp** [comment]
on version 0.0.5 still have a problem because one dependency is still not compatible with nullsafety. Just use version [0.0.6](https://github.com/andriyoganp/blue_print_pos/releases/tag/0.0.6) for compatibility with nullsafety.

**Comment by rafiiAP** [comment]
![Screenshot at 2022-12-28 13-55-49](https://user-images.githubusercontent.com/88351752/209771565-66ca1a7a-ae8a-4263-8bb4-dd021dd0503e.png)
dependences nya sangat membantu sekali bang,. tapi masih ada masalah disini right textstyle namun typenya left style, yang seharusnya typenya right style
