### ISSUE TITLE
No implementation found for method contentToImage on channel webcontent_converter

### ISSUE THREAD

**Issue by sistema5** [andriyoganp/blue_print_pos#20]
Problem printing type error: No implementation found for method contentToImage on channel webcontent_converter

Pressing on the "Test Print" button produces this error. 

querySoundEffectsEnabled...
E/flutter (21719): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Exception: Error: MissingPluginException(No implementation found for method contentToImage on channel webcontent_converter)
E/flutter (21719): #0      WebcontentConverter.contentToImage (package:blue_print_pos/webcontent_converter/webcontent_converter.dart:40:7)
E/flutter (21719): <asynchronous suspension>
E/flutter (21719): #1      BluePrintPos.printReceiptText (package:blue_print_pos/blue_print_pos.dart:121:29)  
E/flutter (21719): <asynchronous suspension>
E/flutter (21719): #2      _MyAppState._onPrintReceipt (package:blue_print_pos_example/main.dart:252:5)
E/flutter (21719): <asynchronous suspension>
E/flutter (21719):

What is this about?

**Comment by andriyoganp** [comment]
Forget to include the native code. Just use on 0.0.8
