### ISSUE TITLE
Small size receipt

### ISSUE THREAD

**Issue by hamzamon** [andriyoganp/blue_print_pos#22]
Hello, The receipt size is is small as shown in attached image, how to fit it according to the paper width?

![receipt-1](https://user-images.githubusercontent.com/26362545/145522464-f2e8f25b-2146-41c6-84be-2147fd4555cf.jpeg)

**Comment by andriyoganp** [comment]
Sorry for late response. I think because of the paper width, the default paper width is used 58mm and hardcoded. I can provide for 72 and 80.

**Comment by andriyoganp** [comment]
@hamzamon Solved in this (#25 )

**Comment by hamzamon** [comment]
Thank you

**Comment by harguus** [comment]
Hello, I have the same problem, my paper is 58mm but the print is coming out as in the ISSUE photo.

Has the solution already been added to the repository?

**Comment by harguus** [comment]
> Sorry for late response. I think because of the paper width, the default paper width is used 58mm and hardcoded. I can provide for 72 and 80.

Hello, I have the same problem, my paper is 58mm but the print is coming out as in the ISSUE photo.

Has the solution already been added to the repository?
