### ISSUE TITLE
Class ReceiptSectionText(). Can Set the paper size 80MM ?

### ISSUE THREAD

**Issue by amonlove** [andriyoganp/blue_print_pos#27]
Class ReceiptSectionText().  Can Set the paper size 80MM ?

**Comment by andriyoganp** [comment]
you can set paper on ```
.printReceiptText(
    ReceiptSectionText receiptSectionText, {
    int feedCount = 0,
    bool useCut = false,
    bool useRaster = false,
    double duration = 0,
    PaperSize paperSize = PaperSize.mm58,
  })
```

But you need to add library [esc_pos_utils_plus](https://pub.dev/packages/esc_pos_utils_plus)

**Comment by amonlove** [comment]
<a href="https://ibb.co/Pt6QC5L"><img src="https://i.ibb.co/Pt6QC5L/errorr.png" alt="errorr" border="0"></a>

I have tried it. but there is error

**Comment by rafiiAP** [comment]
@amonlove add import package:esc_pos_utils_plus sir
