### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by hamzamon** [andriyoganp/blue_print_pos#40]
e: D:\flutter\.pub-cache\hosted\pub.dartlang.org\blue_print_pos-0.0.11\android\src\main\kotlin\com\ayeee\blue_print_pos\BluePrintPosPlugin.kt: (41, 75): One type argument expected for class Result<out T>

FAILURE: Build failed with an exception.

**Comment by andriyoganp** [comment]
Fixed on #41
