### ISSUE TITLE
PaperSize parameter is not working

### ISSUE THREAD

**Issue by Roldification** [andriyoganp/blue_print_pos#54]
Future<void> printReceiptText(
    ReceiptSectionText receiptSectionText, {
    int feedCount = 0,
    bool useCut = false,
    bool useRaster = false,
    double duration = 0,
    PaperSize paperSize = PaperSize.mm58,
  }) async {
    final Uint8List bytes = await contentToImage(
      content: receiptSectionText.content,
      duration: duration,
    );
    final List<int> byteBuffer = await _getBytes(
      bytes,
      paperSize: PaperSize.mm58,
      feedCount: feedCount,
      useCut: useCut,
      useRaster: useRaster,
    );
    _printProcess(byteBuffer);
  }

kindly fix the PaperSize parameter. it is statically set to PaperSize.mm58 we cannot change size because of that. Thanks!

**Comment by andriyoganp** [comment]
Solved in here #52
